config/routes.rb
Turumba::Application.routes.draw do
  
  devise_for :users

  resources :categories
  resources :services
  
  resources :info do
    get 'contact', :on=>:collection
    get 'home', :on=>:collection
  end
  
  root :to => 'info#home'

  
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_and_belongs_to_many :categories
  
  has_many :images, :dependent => :destroy
  
  validates_presence_of :nombre
  
  accepts_nested_attributes_for :images, :reject_if => lambda {|a| a[:data].blank?}, :allow_destroy => true
  
  has_attached_file :logo, 
                      :styles => { :medium => "300x300>",
                                   :thumb => "100x100>" }
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.xml
  
  filter_resource_access
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @services }
    end
  end

  # GET /services/1
  # GET /services/1.xml
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/new
  # GET /services/new.xml
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.xml
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to(@service, :notice => 'Service was successfully created.') }
        format.xml  { render :xml => @service, :status => :created, :location => @service }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.xml
  def update
    params[:service][:category_ids] ||= []
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to(@service, :notice => 'Service was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @service.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.xml
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to(services_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<% content_for :head do%>
<%= javascript_include_tag :ckeditor %>
<% end %>

<%= form_for(@service, :html => { :multipart => true }) do |f| %>
<div class="box radius padded">
	<fieldset class="radius">
		<p>
			<%= f.label :logo %><br />
			<%= f.file_field :logo %>
		</p>
	</fieldset>
	<fieldset class="radius">
		<p>
			<%= f.label :nombre %><br />
			<%= f.text_field :nombre %>
		</p>
	</fieldset>
	<fieldset class="radius">
		<p>
			<%= f.label :descripcion %><br />
			<%= f.cktext_area :descripcion, :toolbar=>'Full', :width=>'400px', :height=>'200px' %>
		</p>
	</fieldset>
	<fieldset class="radius">
		<ul>
			<% for category in Category.all%>
			<li>
				<%= check_box_tag "service[category_ids][]", category.id, @service.categories.include?(category)%>
				<%= category.name%>
			</li>
			<% end %>
		</ul>
	</fieldset>
  
  <%@service.images.each do |img|%>

  <%= image_tag(img.data.url(:thumb))%>

  <%end %>
  
  <%=f.fields_for :images do |builder|%>
	<%=render "image_fields", :f =>builder%>
  <% end %>
  <p><%= link_to_add_fields "Add Image", f, :images %></p>
</div>
<hr class="thin" />
	<%= submit_tag "", :value => "► Save & Proceed", :class => "btn btn-custom radius fr" %>
	
  
<% end %>
<br />

app/views/services/_image_fields.html.erb
<fieldset class="radius fields">
	<p>
	<%=f.file_field :data%>
	<%= link_to_remove_fields "remove", f %><br />
	</p>
</fieldset>

app/views/services/_service.html.erb
<div class="infopanel padded">
		<a class="previewimg nyroModal fl" href="img/hotels/room-1.jpg" title="Hotel Name"><%= image_tag service.logo.url(:thumb) %></a>
		<small class="fr tr"><a href="#">13 reviews</a><br /><b>6.9</b> / 10</small>
		<h3><%= link_to service.nombre, service %> <img src="img/star.png" alt="*" /><img src="img/star.png" alt="*" /><img src="img/star.png" alt="*" /><img src="img/star.png" alt="*" /></h3>
		<div class="address">Address, City [ <a href="#">Show on map</a> ]</div>
		<p><%= service.descripcion %> <a href="#">more &raquo;</a></p>
		<table class="roomlist full">
			<thead>
				<tr>
					<th class="tl w13">Available room types</th>
					<th class="tc w13">Persons</th>
					<th class="tr w13">Rate</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td><a href="#">Single room</a> <span class="label labelred">Last room</span></td>
					<td class="tc">1</td>
					<td class="tr">from <strong class="price">$59.99</strong></td>
				</tr>
				<tr>
					<td><a href="#">Double room</a></td>
					<td class="tc">2</td>
					<td class="tr">from <strong class="price">$74.99</strong></td>
				</tr>
				<tr>
					<td><a href="#">Twin room</a></td>
					<td class="tc">2</td>
					<td class="tr">from <strong class="price">$74.99</strong></td>
				</tr>
			</tbody>
		</table>
		<div class="clear">&nbsp;</div>
	</div>
	<hr class="thin"/>
	

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%=render "form"%>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>

app/views/services/index.html.erb
	<!-- Left column -->
	<div class="grid_4" id="leftcolumn">
		<div class="box radius">
			<!-- Search form -->
			<div class="padded">
				<h2 class="headline radius"><b>Search</b> Services</h2>
				<form name="booking" method="get" action="">
					<!-- calendar image container -->
					<span style="display:none;"><%= image_tag "img/blank.gif",:class=>"trigger"%> </span>
					<fieldset class="radius">
						<p>
							<label class="" for="destination">Where are you going?</label><br/>
							<input type="text" id="destination" class="full" value="" name="destination"/>
						</p>
						<p>
							<label class="" for="startdate">Check in</label><br/>
							<input type="text" id="startdate" class="" value="" name="startdate"/>
							<input type="hidden" name="sd_timestamp" id="sd_timestamp" />
						</p>
						<p>
							<label class="" for="enddate">Check out</label><br/>
							<input type="text" id="enddate" class="" value="" name="enddate"/>
							<input type="hidden" name="ed_timestamp" id="ed_timestamp" /> <span class="nights"></span>
						</p>
						<p><input type="checkbox" id="flexible" class="" value="1" name="flexible"/> <label class="choice" for="flexible">My dates are flexible</label></p>
						<p>
							<label class="" for="adults">How many people?</label><br/>
							Adults <select id="adults" name="adults">
								<option value="1" selected="selected">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
								<option value="4">4</option>
								<option value="5">5</option>
								<option value="6">6</option>
								<option value="7">7</option>
								<option value="8">8</option>
								<option value="9">9</option>
								<option value="10">10</option>
							</select>
							Children <select id="children" name="children">
								<option value="0" selected="selected">0</option>
								<option value="1">1</option>
								<option value="2">2</option>
								<option value="3">3</option>
								<option value="4">4</option>
							</select>
						</p>
						<hr class="thin" />
						<p>
							<label class="" for="sortOrder">Sorted by</label><br/>
							<select id="sortOrder" name="sortOrder">
								<option title="Sort by price - low to high" value="PRICE_ASC">Price - low to high</option>
								<option title="Sort by price - low to high" value="PRICE_DESC">Price - high to low</option>
								<option title="Sort by star rating - high to low" value="STAR_RATING_DESC">Star rating - high to low</option>
								<option title="Sort by star rating - low to high" value="STAR_RATING_ASC">Star rating - low to high</option>
								<option title="Sort by guest rating" value="GUEST_RATING_ASC">Guest rating</option>
							</select>
						</p>
						<input type="submit" class="btn btn-custom radius fr" value="Search &raquo;" />
					</fieldset>
				</form>
			</div>
			<!-- End of Search form -->
			
			<!-- Refine your search boxes -->
			<div class="padded">
				<h2 class="gray radius">Refine your search:</h2>

				<div class="content-box radius">
					<div class="header">Stars</div>
					<div class="section">
						<table class="full">
							<tbody>
								<tr>
									<td><a href="#">1 *</a></td>
									<td class="tr"><small>11 hotels</small></td>
								</tr>
								<tr>
									<td><a href="#">2 **</a></td>
									<td class="tr"><small>2 hotels</small></td>
								</tr>
								<tr>
									<td><a href="#">3 ***</a></td>
									<td class="tr"><small>21 hotels</small></td>
								</tr>
								<tr class="selected">
									<td>4 ****</td>
									<td class="tr"><a href="#" title="uncheck">x</a></td>
								</tr>
								<tr>
									<td><a href="#">5 *****</a></td>
									<td class="tr"><small>3 hotels</small></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="content-box radius">
					<div class="header">Price Range ($)</div>
					<div class="section">
						<table class="full">
							<tbody>
								<tr>
									<td><a href="#">0 - 49</a></td>
									<td class="tr"><small>3 hotels</small></td>
								</tr>
								<tr class="selected">
									<td>50 - 99</td>
									<td class="tr"><a href="#" title="uncheck">x</a></td>
								</tr>
								<tr>
									<td><a href="#">100 - 149</a></td>
									<td class="tr"><small>2 hotels</small></td>
								</tr>
								<tr>
									<td><a href="#">150 - 199</a></td>
									<td class="tr"><small>12 hotels</small></td>
								</tr>
								<tr>
									<td><a href="#">200+</a></td>
									<td class="tr"><small>11 hotels</small></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
				<div class="content-box radius">
					<div class="header">Hotel Type</div>
					<div class="section">
						<table class="full">
							<tbody>
								<tr>
									<td><a href="#">Apartment</a></td>
									<td class="tr"><small>1 hotel</small></td>
								</tr>
								<tr>
									<td><a href="#">Guest accommodation</a></td>
									<td class="tr"><small>51 hotels</small></td>
								</tr>
								<tr>
									<td><a href="#">Hotel</a></td>
									<td class="tr"><small>29 hotels</small></td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
			<!-- End of Refine your search boxes -->

			
		</div>
		<div class="">&nbsp;</div>
		
	
	</div>
	<!-- End of Left column -->
	
	<!-- Right column -->
	<div class='grid_8 searchpanel'>
		<h1>Servicios</h1>

		<br />
		<%= link_to 'Nuevo Servicio', new_service_path %>
		<h3 class="">81 Hotels found, 48 Available</h3>
		
		<p><span class="fr"><a href="#">&lt; Previous page</a> | <a href="#">Next page &gt;</a></span> <b>Showing 1 – 10</b></p>
		<p class="box padded">
			Sort by: <b>price (low to high)</b> &middot; <a href="#">price (high to low)</a> &middot; <a href="#">popularity</a> &middot; <a href="#">stars (1..5)</a> &middot;  <a href="#">stars (5..1)</a> &middot; <a href="#">review score</a>
		</p>
		
		<!-- Search item -->
		
	<%= render @services %>

		<!-- End of Search item -->
		
		
	

		<p class="box padded"><span class="fr"><a href="#">Next page &gt;</a></span><a href="#">&lt; Previous page</a></p>
		
		<p>&nbsp;</p>
		<!-- Shortcut buttons -->
		<div class="fr">
			<button class="box radius" title="Print this page" onclick="window.print();"><img src="img/print.gif" alt="Print" /></button>
			<button class="box radius" title="Email to a friend"><img src="img/email.gif" alt="Email" /></button>
			<button class="box radius" title="Bookmark"><img src="img/bookmark.gif" alt="Bookmark" /></button>
		</div>
		<!-- End of Shortcut buttons -->
		
		<div class="clear">&nbsp;</div>
	
	</div>
	
	<p>&nbsp;</p>
	<div class="clear">&nbsp;</div>
	
</div>

app/views/services/new.html.erb
<% content_for :head do%>
<%= javascript_include_tag :ckeditor %>
<% end %>



<%= link_to 'Regresar', services_path %>


<!-- Left column: Checkout Steps -->
<div class="grid_8">
	<!-- Steps -->
	<table class="full">
		<tbody>
			<tr>
				<td class="w13">
					<!-- Selected/stepped -->
					<div class="steps stepped radius-left">
						<h4>Step 1.</h4>
						Nuevo Servicio
					</div>
					<div class="triangle"></div>
				</td>
				<td class="w13">
					<div class="steps">
						<h4>Step 2.</h4>
						Rooms &amp; Guest Details
					</div>
				</td>
				<td class="w13">
					<div class="steps radius-right">
						<h4>Step 3.</h4>
						Confirmation
					</div>
				</td>
			</tr>
		</tbody>
	</table>
	<!-- End of Steps -->
	
		<% if @service.errors.any? %>
		    	<div class="alert">
		      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

		      <ul>
		      <% @service.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

	<!-- Checkout form -->
	
		<%=render "form"%>
	
	<!-- End of Checkout form -->
</div>
<!-- End of Left column: Checkout Steps -->

<!-- Right column: Charges -->
<div class="grid_4">
	<div class="infopanel">			
		<h6>Room Charges</h6>
		<h3><a href="#">Hotel Name ****</a></h3>
		<table class="full">
			<tbody>
				<tr>
					<td><b>Room:</b></td>
					<td>Superior Double Room</td>
				</tr>
				<tr>
					<td><b>Adults:</b></td>
					<td>2</td>
				</tr>
				<tr>
					<td><b>Children:</b></td>
					<td>0</td>
				</tr>
				<tr>
					<td><b>Check-in:</b></td>
					<td>Saturday, August 7, 2010</td>
				</tr>
				<tr>	
					<td><b>Check-out:</b></td>
					<td>Sunday, August 8, 2010</td>
				</tr>
				<tr>
					<td><b>Nights:</b></td>
					<td>1</td>
				</tr>
				<tr>
					<td><b>Total room price:</b></td>
					<td><b>$25.00</b></td>
				</tr>
			</tbody>
		</table>
		<h6>Total Charges</h6>
		<table class="full">
			<tbody>
				<tr>
					<td>Room Subtotal:</td>
					<td class="tr">$25.00</td>
				</tr>
				<tr>
					<td>Tax &amp; Fees:</td>
					<td class="tr">$3.20</td>
				</tr>
				<tr>
					<td colspan="2"><hr class="thin" /></td>
				</tr>
				<tr>
					<td><b>TOTAL:</b></td>
					<td class="tr"><span class="color-green big"><b>$28.20</b></span></td>
				</tr>
			</tbody>
		</table>
		<h6>Cancellation Policy</h6>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
	</div>
</div>
<!-- End of Right column: Charges -->