config/routes.rb
Turumba::Application.routes.draw do
  
  devise_for :users

  resources :categories
  resources :services
  
  resources :info do
    get 'contact', :on=>:collection
    get 'home', :on=>:collection
  end
  
  root :to => 'info#home'

  
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container_12 padded">
		<div class="grid_3">
			<h3>Online Booking</h3>
			<p class="small">Copyright &copy; 2010 <b>Company Name</b><br />All rights reserved.</p>
			<p class="small">Book online or call: <b>1-800-123-456789</b></p>
			<a href="#"><img src="img/social/twitter.png" alt="twitter" /></a> 
			<a href="#"><img src="img/social/facebook.png" alt="facebook" /></a> 
			<a href="#"><img src="img/social/flickr.png" alt="flickr" /></a>
			<a href="#"><img src="img/social/youtube.png" alt="YouTube" /></a>
			<a href="#"><img src="img/social/rss.png" alt="RSS" /></a>
			<p class="small"><a href="#">Sitemap</a> &middot; <a href="#">Blog</a></p>
		</div>
		<div class='grid_3'>
			<h3>Suppliers, Affiliates, Media</h3>
			<ul>
				<li><a href="#">Add Hotel</a></li>
				<li><a href="#">Affiliate With Us</a></li>
				<li><a href="#">Promote With Us</a></li>
				<li><a href="#">Travel Agents</a></li>
				<li><a href="#">Press Office</a></li>
			</ul>
		</div>
		<div class='grid_3'>
			<h3>About</h3>
			<ul>
				<li><a href="#">About Us</a></li>
				<li><a href="#">Partners</a></li>
				<li><a href="#">Customer Service</a></li>
				<li><a href="#">FAQ</a></li>
				<li><a href="#">Terms &amp; Conditions</a></li>
				<li><a href="#">Privacy Statement</a></li>
			</ul>
		</div>
		<div class='grid_3'>
			<h3>Affiliate/Partner Login</h3>
			<form name="login" action="">
				<p>
					<label class="" for="email">Email</label><br/>
					<input type="text" id="email" class="full" value="" name="email"/>
				</p>
				<p>
					<label class="" for="password">Password</label><br/>
					<input type="password" id="password" class="full" value="" name="password"/>
				</p>
				<p>
					<input type="checkbox" id="remember" class="" value="1" name="remember" />
					<label class="choice" for="remember">Remember me</label>
				</p>
				<input type="submit" class="btn radius fr" value="Sign in &raquo;" />
			</form>
		</div>
		<div class="clear">&nbsp;</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="grid_12">
		<!-- Logo container -->
		<div id="logo"></div>
		
		<!-- Aside menu -->
		<div id="topmenu" class="tr">
			<% if user_signed_in? %>
				<%= link_to "Log out", destroy_user_session_path %> | 
			<% else %>
				<%= link_to "Sign in", new_user_session_path %> | 
			<% end%>
			<%= link_to "Registrate", new_user_registration_path %>
			
			
			
		</div>
		<!-- End of Aside menu -->
		
		<!-- Main navigation -->
		<div class="radius" id="navigation">
			<ul id="nav">
				<li class="current_page_item"><%= link_to "Home", root_path%></li>
				<li class="">
					<%= link_to "Categories", categories_path%>
					<!-- Dropdown menu -->
					<div class="dropdown_submenu tripple">
						<ul>
							<li class="dropdown_heading">Worldwide</li>
							<li><a href="#">North America</a></li>
							<li><a href="#">South America</a></li>
							<li><a href="#">Australia</a></li>
							<li><a href="#">Africa</a></li>
							<li><a href="#">Asia</a></li>
							<li><a href="#">Europe</a></li>
						</ul>
						<ul>
							<li class="dropdown_heading">Top Countries</li>
							<li><a href="#">USA</a></li>
							<li><a href="#">Italy</a></li>
							<li><a href="#">Netherlands</a></li>
							<li><a href="#">France</a></li>
							<li><a href="#">Singapore</a></li>
							<li><a href="#">Spain</a></li>
						</ul>
						<ul>
							<li class="dropdown_heading">Top Cities</li>
							<li><a href="#">Dubai</a></li>
							<li><a href="#">Rome</a></li>
							<li><a href="#">Dublin</a></li>
							<li><a href="#">Las Vegas</a></li>
							<li><a href="#">Singapore</a></li>
							<li><a href="#">Amsterdam</a></li>
						</ul>
						<a class="dropdown_subfoot" href="#">Browse destinations &raquo;</a>
					</div>				
					<!-- End of Dropdown menu -->
				</li>
				<li class=""><%= link_to "Services", services_path%></li>
				<li class=""><a title="Vacation Ideas" href="#">Vacation Ideas</a></li>
				<li class="separator">&nbsp;</li>
				<li class=""><%= link_to "Contact", contact_info_index_path%></li>
				<li class="separator">&nbsp;</li>
				<li class="">
					<a title="My Bookings" href="#">Sample Pages</a>
					<!-- Dropdown menu -->
					<div class="dropdown_submenu double">
						<ul>
							<li class="dropdown_heading">Hotels</li>
							<li><a href="index.htm">Homepage</a></li>
							<li><a href="search.htm">Search hotels</a></li>
							<li><a href="browse.htm">Browse destinations</a></li>
							<li><a href="hotel.htm">Hotel data</a></li>
							<li><a href="print-map.htm">Print preview</a></li>
							<li><a href="checkout.htm">Checkout</a></li>
						</ul>
						<ul>
							<li class="dropdown_heading">Misc</li>
							<li><a href="contact.htm">Contact page</a></li>
							<li><a href="faq.htm">FAQ</a></li>
							<li><a href="full.htm">Full width page</a></li>
							<li><a href="sitemap.htm">Sitemap</a></li>
							<li><a href="typography.htm">Typography</a></li>
						</ul>
					</div>				
					<!-- End of Dropdown menu -->
				</li>
			</ul><!-- /#nav -->
		</div>
		<!-- End of Main navigation -->
		
</div>

app/views/layouts/_navbar.html.erb
<div id="wrapper" class="hfeed">
<div id="user_nav">
		<% if user_signed_in?%>
		Logged in as <%= current_user.email%>
		<%= link_to "Log Out", destroy_user_session_path%>
		<% else %>
		<%= link_to "Sign up", new_user_registration_path %>
		<%= link_to "log in", new_user_session_path %>
		<% end %>
	</div>

	<div id="header">
		<div id="masthead">
			<div id="branding">
	
				<div id="site-description">
				
				</div>
				
<%=link_to  image_tag("turumbalogo.png", :alt => "", :class =>"redondeado"),services_url()%>
			</div><!-- #branding -->

	<div id="access">
		<div class="skip-link screen-reader-text">
			<a href="#content"title="Skip to content">Skip to content</a>
		</div>
		<div class="menu-header">
			<ul id="menu-menu-principal"class="menu">
				<li id="menu-item-1" class="menu-item menu-item-type-custom">
					<%=link_to "Servicios", services_url()%>
					
					<ul class="sub-menu">										
						<li id="menu-item-2" class="menu-item menu-item-type-post_type ultimo">
						<%=link_to "Servicios", services_url()%>
						</li>						
					</ul>
				</li>				
			</ul>
			<ul id="menu-menu-principal"class="menu">
				<li id="menu-item-1" class="menu-item menu-item-type-custom">
					<%=link_to "Categorias", categories_url()%>
					
					<ul class="sub-menu">										
						<li id="menu-item-2" class="menu-item menu-item-type-post_type ultimo">
						<%=link_to "Category", categories_url()%>
						</li>						
					</ul>
				</li>				
			</ul>
		</div>
	</div><!-- #access -->
</div><!-- #masthead -->
</div><!-- #header -->

app/views/layouts/_subfooter.html.erb
<div id="subfooter">
	<div class="container_12 padded">
		<div class='grid_12'>
			<h5>Reasons for choosing us</h5>
		</div>
		<div class='grid_3'><b>Low rates</b><br />Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</div>
		<div class='grid_3'><b>Maximum choice</b><br />Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</div>
		<div class='grid_3'><b>Satisfied guests</b><br />Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</div>
		<div class='grid_3'><b>We speak your language</b><br />Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
		<div class="clear">&nbsp;</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Todo Para tu Rumba</title>	
	
	<!-- Meta tags -->
	<meta http-equiv="content-language" content="en-us" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<meta http-equiv="Content-Style-Type" content="text/css" />	
	<meta http-equiv="window-target" content="_top" /> <!-- skip frames -->
	<meta name="robots" content="index,follow" />
	<meta name="keywords" content="booking, hotel, hotels, reservations" />
	<meta name="description" content="Online Booking" />
	
	<!-- Favicons --> 
	<link href="img/favicon.png" rel="shortcut icon" type="image/png" />
	<link href="img/favicon.png" rel="icon" type="image/png" />
	
	<!-- Main Stylesheets -->
	<%= stylesheet_link_tag "css/style" %>
	<%= stylesheet_link_tag "css/extensions" %> <!-- browser specific extensions / remove it if you want to validate this document --> 
	<%= stylesheet_link_tag "css/print", :media => "print" %><!-- for printing -->
	<!-- Alternate stylesheets/themes -->
	<%= stylesheet_link_tag "css/green" %>
	
	<!-- Your Custom Stylesheet --> 
	<%= stylesheet_link_tag "css/custom" %>
	
	<!-- RSS links (if needed) -->
	<link href="top.rss" rel="alternate" type="application/rss+xml" title="Top Destinations" />
	<link href="deals.rss" rel="alternate" type="application/rss+xml" title="Best Deals" />
	<link href="blog.rss" rel="alternate" type="application/rss+xml" title="Latest News" />
	
	<!-- jQuery with plugins -->
	<%= javascript_include_tag :defaults %> <!-- Could be loaded remotely from Google CDN : <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script> -->
	<!-- Pretty Photo -->
	<%= javascript_include_tag "prettyPhoto/js/jquery.prettyPhoto"%>
	<%= stylesheet_link_tag 'css/prettyPhoto' %>
	<!-- END Pretty Photo -->
	<%= javascript_include_tag "js/jquery.ui.core.min"%>
	<%= javascript_include_tag "js/jquery.ui.widget.min"%>
	<%= javascript_include_tag "js/jquery.datepick.pack"%>
	<%= javascript_include_tag "js/jquery.datepick-en-GB"%>
	<%= javascript_include_tag "js/jquery.imgpreview"%>
	<%= javascript_include_tag "js/jquery.nyroModal.pack" %>
	<%= javascript_include_tag "js/jquery.notice"%>
	<%= javascript_include_tag "js/jquery.cycle.pack"%>
	<%= javascript_include_tag "js/jquery.notice"%>
	
	
	<!-- Google maps and marker clustering -->
	<script src="http://www.google.com/jsapi?autoload={'modules':[{name:'maps',version:3,other_params:'sensor=false'}]}" type="text/javascript"></script>
	<%= javascript_include_tag "js/Fluster2.packed"%>
	
	<!-- Custom template functions -->
	<%= javascript_include_tag "js/custom"%>
	
	<!-- Style switcher : only needed here for theme demonstration (does not work in IE7) -->
	<%= javascript_include_tag "js/styleswitch"%>
	
	
	<!-- Internet Explorer Fixes --> 
	<!--[if IE]>
	<link rel="stylesheet" type="text/css" media="all" href="css/ie.css"/>
	<![endif]-->
	<!--Upgrade MSIE5.5-7 to be compatible with MSIE8: http://ie7-js.googlecode.com/svn/version/2.1(beta3)/IE8.js -->
	<!--[if lt IE 8]>
	<script src="js/IE8.js"></script>
	<![endif]-->
	
	<script type="text/javascript">
	//<![CDATA[
	
	// check-out date >= check-in date
	function customRange(dates) { 
		if (this.id == 'startdate') { 
			$('#enddate').datepick('option', 'minDate', dates[0] || null); 
		} 
		else { 
			$('#startdate').datepick('option', 'maxDate', dates[0] || null); 
		}
		var edt = $('#ed_timestamp').val();
		var sdt = $('#sd_timestamp').val();
		if ((edt > 0) && (sdt > 0)) {
			$('span.nights').text((edt - sdt) / (3600*24) + ' night(s)');
		} else {
			$('span.nights').text('');
		}
	}
	
	$(document).ready(function(){
		
		// Datepick input fields
		$('#startdate').datepick({
			onSelect: customRange, 
			showTrigger: '#trigger',
			altField: '#sd_timestamp', 
			altFormat: $.datepick.TIMESTAMP
		});
		$('#enddate').datepick({
			onSelect: customRange, 
			showTrigger: '#trigger',
			altField: '#ed_timestamp', 
			altFormat: $.datepick.TIMESTAMP
		});
		
		// Carousel slider
		$('.carousel ul').cycle({
			prev: '.previous',
			next: '.next',
			timeout: 6000,
			pause: 1
		});
		
		/* tabs */
		var tabs = $("#tabs").tabs();		
		
		// Template setup
		Site.setup();
		
		// Google map setup
		// centerX: 27.9944
		// centerY: -9.84375
		// zoom: 2
		// clustering: true
		// NOTE: hotel list is loaded on the bottom of this file
		Site.gmapInit(27.9944, -9.84375, 2, true);
		
	});
	
	//]]>
	</script>
	<%= csrf_meta_tag %>
	<%= yield :head %>
</head>

<body>
	
<div class="container container_12">
	<!-- Header -->
	
	<%= render :partial => 'layouts/header' %>

	<!-- End of Header -->

	<!-- Body -->
	
	<%= yield %>
	
	
	<!-- End Body -->
	

	<!-- End of Info boxes -->


	
</div>

<!-- Subfooter -->
<%= render :partial => 'layouts/subfooter' %>

<!-- End of Subfooter -->

<!-- Footer -->
<%= render :partial => 'layouts/footer' %>
<!-- End of Footer -->

<!-- Scroll to top link -->
<a href="#" id="totop" class="radius" title="back to top"><img src="img/top.png" alt="back to top" /></a>



</body>
</html>

app/views/layouts/application3.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Turumba</title>
	<%= stylesheet_link_tag :all %>
	<%= javascript_include_tag :defaults %>
	<%= stylesheet_link_tag 'css/prettyPhoto', 'style' %>
	<%= javascript_include_tag "prettyPhoto/js/jquery.prettyPhoto"%>
	<%= csrf_meta_tag %>
	<%= yield :head %>
</head>
<body class="home blog">

	<%= render :partial => "layouts/navbar" %>

	<div id="main">
		<% flash.each do |name, msg|%>
			<%= content_tag :div, msg, :id=> "flash_#{name}"%>
		<% end %>
		<div id="container">
			<div id="content">

			<%= yield %>

		</div>	
	</div>
	<div id="primary" class="widget-area">
	<%= yield  :widget%>
	<%=link_to  image_tag("p.png",:size => "200x589"), services_url()%>
	
</div>
</div>

<div id="footer">
	<div id="colophon">
		<div id="site-info">
			
		</div>
		<div id ="site-generator">
			<p>Turumba.com</p>
		</div>
	</div>
</div>

</div>

</body>
</body>
</html>